from django.db import models

DRAFT, VERIFICATION_SENT, VERIFICATION_SUCCESS = 0, 1, 2


class NewsStatus(models.IntegerChoices):
    DRAFT = DRAFT, 'DRAFT'
    VERIFICATION_SENT = VERIFICATION_SENT, 'VERIFICATION_SENT'
    VERIFICATION_SUCCESS = VERIFICATION_SUCCESS, 'VERIFICATION_SUCCESS'
