# Generated by Django 4.2.9 on 2024-01-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True),
        ),
    ]
